@endpoint = http://static.smallsaas.cn
# @endpoint = http://localhost:8080

### 查看路由
GET {{endpoint}}/dev/auto/forms/5555599/routes/1

### 添加新路由
POST {{endpoint}}/dev/auto/forms/5555599/routes
{
    "img": "http://static.smallsaas.cn/house/2022/svg/senior/communityConfig.svg",
    "nav": "/pages/my/seniorConfig/index?id=8890",
    "color": "###207f4c",
    "title": "社区配置123"
}


### 修改指定位置路由, 可任意变更其中一个属性
#PUT {{endpoint}}/dev/auto/route/5555599
PUT {{endpoint}}/dev/auto/forms/5555599/routes/1
{
    "img": "http://static.smallsaas.cn/house/2022/svg/senior/communityConfig.svg",
    "nav": "/pages/my/seniorConfig/index?id=8890",
    "color": "###207f4c",
    "title": "社区配置12"
}


### 变更路由跳转页面  如果多个参数有数字的请把pageId写在第一位
POST {{endpoint}}/dev/auto/forms/5555599/routes/1/op/next

{
   "pageid": 42342432
}


### 移动指定路由项
POST {{endpoint}}/dev/auto/forms/5555599/route/op/arrange

{
    "from": 0,
    "to": 2
}

### 移除指定路由项
POST {{endpoint}}/dev/auto/forms/5555599/route/op/remove

{
    "index":1
}


### 复制指定路由项 index
POST {{endpoint}}/dev/auto/forms/5555599/route/op/copy

{
    "index":2
}