@endpoint = http://static.smallsaas.cn


### 修改指定位置路由  index从0开始
PUT {{endpoint}}/dev/auto/route/5555599
{
    "index":1,
    "img": "http://static.smallsaas.cn/house/2022/svg/senior/communityConfig.svg",
    "nav": "/pages/my/seniorConfig/index?id=8890",
    "color": "###207f4c",
    "title": "社区配置1"
}

###移动位置  index 为当前位置 target是要指定的位置
PUT {{endpoint}}/dev/auto/route/position/5555599
{
    "index":0,
    "target":2
}


### 添加路由 index为指定路由位置
PUT {{endpoint}}/dev/auto/route/add/5555599
{
    "index":0,
    "img": "http://static.smallsaas.cn/house/2022/svg/senior/communityConfig.svg",
    "nav": "/pages/my/seniorConfig/index?id=8890",
    "color": "###207f4c",
    "title": "社区配置12"
}


### 移除路由 index为指定路由位置
PUT {{endpoint}}/dev/auto/route/remove/5555599
{
    "index":3
}


### 复制路由 index 为要被复制的路由位置 target 位置到的位置
PUT {{endpoint}}/dev/auto/route/copy/5555599
{
    "index":0,
    "target":3
}